# root: true
# enable ES6
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true # enable React's JSX

# register plugins
plugins:
  - meteor

# use the rules of eslint-config-airbnb
# and the recommended rules of eslint-plugin-meteor
extends:
  - airbnb-base

# registerenvironments
env:
  browser: true
  node: false
  es6: true

rules:
  semi: [2, 'never']
  no-unexpected-multiline: 2
  no-throw-literal: 0
  import/no-extraneous-dependencies: 0
  import/no-absolute-path: 0
  import/extensions:
    - off
    - never
